name: update doxygen files and publish pages 
  
on:  
  push:  
    branches:  
      - CI/CD  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
      
    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v2  
        
    - name: Install Doxygen  
      run: sudo apt-get install -y doxygen  
        
    - name: Generate Doxygen documentation  
      run: doxygen Doxyfile  
        
    - name: Upload Doxygen artifacts  
      uses: actions/upload-artifact@v2  
      with:  
        name: Doxygen Documentation  
        path: ./html  
    - name: Move artifacts to GitHub Pages directory  
      run: |  
        mkdir -p ./docs/doxygen  
        mv ./html/* ./docs/doxygen  
    - name: Trigger GitHub Pages update  
      uses: peaceiris/actions-gh-pages@v3  
      with:  
        github_token: ${{ secrets.GITHUB_TOKEN }}  
        publish_dir: ./docs  
