name: Update Doxygen Files and Publish Pages  
  
on:  
  push:  
    branches:  
      - CI/CD  
  
jobs:  
  build:  
    runs-on: windows-latest  
        
    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v2  
          
    - name: Install Doxygen  
      run: choco install doxygen.portable -y  
          
    - name: Generate Doxygen documentation  
      run: doxygen Doxy  
          
    - name: Upload Doxygen artifacts  
      uses: actions/upload-artifact@v2  
      with:  
        name: Doxygen Documentation  
        path: ./html  
          
    - name: Move artifacts to GitHub Pages directory  
      run: |  
        mkdir .\docs  
        move .\html\* .\docs  
          
    - name: Trigger GitHub Pages update  
      uses: peaceiris/actions-gh-pages@v3  
      with:  
        github_token: ${{ secrets.GITHUB_TOKEN }}  
        publish_dir: ./docs  
